name: Generate Total Commit Badge

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count commits
        uses: actions/github-script@v7
        id: commits
        with:
          script: |
            const username = 'NiteeshL';
            const allRepos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
            });

            let total = 0;
            for (const repo of allRepos) {
              try {
                const stats = await github.rest.repos.getContributorsStats({
                  owner: username,
                  repo: repo.name,
                });
                const me = stats.data?.find(user => user.author?.login === username);
                if (me) total += me.total;
              } catch (e) {
                console.log(`Skipping ${repo.name}: ${e.message}`);
              }
            }

            console.log(`Total commits: ${total}`);
            return total;

      - name: Generate badge
        uses: jaywcjlove/create-badge@main
        with:
          label: Total Commits
          message: ${{ steps.commits.outputs.result }}
          color: green
          style: flat
          path: commits-badge.svg

      - name: Commit badge to repo
        run: |
          mkdir -p badges
          mv commits-badge.svg badges/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/commits-badge.svg
          git commit -m "Update commit badge" || echo "No changes to commit"
          git push
