name: Generate Total Commit Badge

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Count commits
        uses: actions/github-script@v7
        id: commits
        with:
          script: |
            const username = 'NiteeshL';
            const allRepos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
            });

            let total = 0;
            for (const repo of allRepos) {
              const commits = await github.rest.repos.getContributorsStats({
                owner: username,
                repo: repo.name,
              });
              const me = commits.data.find(user => user.author?.login === username);
              if (me) {
                total += me.total;
              }
            }

            console.log(`Total commits: ${total}`);
            return total;

      - name: Generate badge
        uses: jaywcjlove/github-action-badge@main
        with:
          label: Total Commits
          message: ${{ steps.commits.outputs.result }}
          color: green
          style: flat
          file: commits-badge.svg

      - name: Upload badge
        uses: actions/upload-artifact@v4
        with:
          name: commit-badge
          path: commits-badge.svg
