name: Update commit badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Count commits (private + public)
        id: commits
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const username = 'NiteeshL';
            const repos = await github.paginate(github.rest.repos.listForAuthenticatedUser, {
              visibility: 'all',
              affiliation: 'owner',
              per_page: 100,
            });
      
            let totalCommits = 0;
      
            for (const repo of repos) {
              if (repo.archived) continue;
      
              try {
                const commits = await github.paginate(github.rest.repos.listCommits, {
                  owner: username,
                  repo: repo.name,
                  author: username,
                  per_page: 100,
                });
      
                console.log(`${repo.name}: ${commits.length}`);
                totalCommits += commits.length;
      
              } catch (e) {
                console.log(`Skipping ${repo.name}: ${e.message}`);
              }
            }
      
            console.log("✅ Total commits (including private):", totalCommits);
            return totalCommits;


      - name: Save JSON for badge
        run: |
          mkdir -p badges
          echo '{ "schemaVersion": 1, "label": "Total Commits", "message": "${{ steps.commits.outputs.result }}", "color": "green" }' > badges/commits-badge.json

      - name: Commit badge JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/commits-badge.json
          git commit -m "Update commits badge JSON" || echo "No changes to commit"
          git push
