name: Update commit badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count commits
        id: commits
        uses: actions/github-script@v7
        with:
          script: |
            const username = 'NiteeshL';
            const allRepos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
            });

            let total = 0;
            for (const repo of allRepos) {
              try {
                const stats = await github.rest.repos.getContributorsStats({
                  owner: username,
                  repo: repo.name,
                });
                const me = stats.data?.find(user => user.author?.login === username);
                if (me) total += me.total;
              } catch (e) {
                console.log(`Skipping ${repo.name}: ${e.message}`);
              }
            }

            console.log("Total commits:", total);
            return total;

      - name: Save JSON for badge
        run: |
          mkdir -p badges
          echo '{ "schemaVersion": 1, "label": "Total Commits", "message": "${{ steps.commits.outputs.result }}", "color": "green" }' > badges/commits-badge.json

      - name: Commit badge JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/commits-badge.json
          git commit -m "Update commits badge JSON" || echo "No changes to commit"
          git push
