name: Generate Total Commit Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count commits
        id: commit_count
        uses: actions/github-script@v7
        with:
          script: |
            const username = 'NiteeshL';
            const allRepos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
            });

            let total = 0;
            for (const repo of allRepos) {
              try {
                const stats = await github.rest.repos.getContributorsStats({
                  owner: username,
                  repo: repo.name,
                });
                const me = stats.data?.find(user => user.author?.login === username);
                if (me) total += me.total;
              } catch (e) {
                console.log(`Error on ${repo.name}: ${e.message}`);
              }
            }

            console.log("Total commits:", total);
            return total;
      
      - name: Install badge generator
        run: npm install -g @jaywcjlove/create-badge

      - name: Generate badge
        run: |
          mkdir -p badges
          npx create-badge \
            --label "Total Commits" \
            --message "${{ steps.commit_count.outputs.result }}" \
            --color "green" \
            --style "flat" \
            --output badges/commits-badge.svg

      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/commits-badge.svg
          git commit -m "Update total commit badge" || echo "No changes"
          git push
